pipeline {
    agent none
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['qa', 'dev', 'prod'], description: 'pipeline on different node')
    }


    tools{
        jdk 'java-11'
        maven 'maven'
    }
    
    stages {
        stage('Checkout') {
            agent {
                label 'qa'
            }

            steps {
                echo "Checkout the code"
                git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/test-1.git'
            }
        }

        stage('Build & Test') {
            parallel {
                stage('Build') {
                    agent any
                    steps {
                        echo "Building Maven project"
                        sh 'mvn clean install'
                    }
                }
                stage('Unit Testing') {
                    agent any
                    steps {
                        echo "Running unit tests"
                        sh 'mvn test'
                    }
                }
            }
        }

        stage('Deploy') {
            agent any
            steps {
                echo "Deploying to ${params.ENVIRONMENT}"
            }
        }
    }
}
