pipeline{
    agent none

    stages{
        stage('checkout'){
            agent {
                label 'qa'
            }

            steps{
                echo "chekou the code"
                git branch:'main', url: 'https://github.com/ManojKRISHNAPPA/test-1.git'
            }
        }

        stage('Build & test'){
            agent any
            steps{
                echo "chekou the code"
                git branch:'main', url: 'https://github.com/ManojKRISHNAPPA/complete-cicd-project-microdegree.git'
            }            
        }
    }
}